### ISSUE TITLE
BUG-Hotseat not changing color for active player

### ISSUE THREAD

**Issue by kourepai** [rogeriocamorim/duneBugSuggestionTracker#20] opened 2023-12-25 16:42 UTC
In hotseat mode, when pressing the end turn button sometimes, although it will go to the next player, the color will not change. For example. by pressing end turn for yellow, the turn will be passed to blue, but the color will stay yellow, thus having to change it manually.

**Comment by Chatanga** [comment] 2024-01-02 13:35
I am unable to reproduce this behavior. If it's not completely random, I'm definitely missing some context information.

**Comment by kourepai** [comment] 2024-01-02 17:27
It seems random to me but it happens almost every game. Would it help if I made a video? Something else maybe?

**Comment by Chatanga** [comment] 2024-01-02 20:49
~~Yes, that would be helpful, at least to clear up any misunderstandings about the context. By the way, any error or strange message in the system log?~~

**Comment by Chatanga** [comment] 2024-01-03 20:56
~~1. Did your system log contains a message "No player seated where there should be one!"?~~
~~2. Are you playing with a high/variable FPS monitor (not the good old 60 Hz)?~~

**Comment by Chatanga** [comment] 2024-01-04 18:20
Fixed in [Fxed hotseat not changing color for active player.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/166d5988507d1289db146ffd9d2f0a4d1431099a)

**Comment by Tarpsukka** [comment] 2024-01-07 08:50
Playing hotseat frequently and this problem still exists.

**Comment by aaittouares** [comment] 2024-01-07 23:38
@Chatanga isn't this fixed with the new revisited version ??
https://github.com/aaittouares/Dune_Uprising_TTS/commit/7a146f0bfe307cadbbccf978d1fcea86bba6f70b
This commit is not yet on public version
I'm actually deploying it @Tarpsukka please report in the next days if you still have this issue, else i will close this issue at end of week

**Comment by kourepai** [comment] 2024-01-08 11:55
Hi, I just played and had the same problem again. I am attaching a picture of the log.  The active player is yellow while it is blue's turn.
![image](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/23338290/81ee0d79-e620-45be-8d53-125b05ec0da7)

However it is much better, because it is not persistent. Meaning, that after I change the color then it will work again, while before it was completely unsynced. However it still happens after a while.

**Comment by Chatanga** [comment] 2024-01-08 16:23
Unfortunately, my solution was not enough and it is still relevant today. The good news is that I know exactly what's going on now.

**Comment by Chatanga** [comment] 2024-01-12 20:40
[Fixed issues:](https://github.com/aaittouares/Dune_Uprising_TTS/commit/1bbac1e5027e986b2cc15d300448f15a690f72e1)
- Error which breaks turns when loading a save.
- Hotseat not changing color for active player.
Enhancements:
- Alternate "Take Place" / "End Turn" button in hotseat.
- Smart player switch in hotseat with 2 players (in 4P and 6P modes).

**Closed as completed** 2024-03-17 09:25 UTC
