### ISSUE TITLE
Suggestion: more elegant way of acquiring HC with Corrinth City

### ISSUE THREAD

**Issue by 4thQueen** [rogeriocamorim/duneBugSuggestionTracker#35] opened 2024-01-22 15:33 UTC
I discovered that there is no easy way to use Corrinth City's on-reveal effect of acquiring a seat on the High Council. As a reminder, Corrinth City's reveal states "Gain 5 Solari - OR - Spend 5 Solari to gain a seat on the High Council"

However, in order to do this, you have to first manually recall an agent, then remove any agents from the HC space, if any, then click on HC as if it were your turn, then return that agent to the space it was on originally.

That kinda sucks.

Any chance of adding either a button to the space where the HC tokens show up or additional functionality to manually acquire a HC seat? Not sure what an elegant solution looks like, but hopefully something that doesnt require four steps. Thanks.

**Comment by rogeriocamorim** [comment] 2024-01-22 16:13
There is a button for that
![image](https://github.com/rogeriocamorim/duneBugSuggestionTracker/assets/1370987/9b714a3d-ef3c-41c3-916a-1607753b8f1e)

**Comment by 4thQueen** [comment] 2024-01-22 16:28
Clicking the token itself? I did try that... guess it was just a stray bug then. Carry on.

**Comment by Chatanga** [comment] 2024-01-22 20:09
4thQueen is not hallucinating. The button does exist, but it disappears after a reload and only reappears during the next recall phase. The issue is fixed and will be part of the next release I assume.

Fixed in [Added protection against illicit module access.](https://github.com/aaittouares/Dune_Uprising_TTS/commit/85f14e85f96f267fe97e819dc1eaa1d5777f8e69)

**Comment by rogeriocamorim** [comment] 2024-03-11 19:37
Released.

**Closed as completed by rogeriocamorim** 2024-03-11 19:37 UTC
Labels: waiting-release
